<?php

return [
    'api_base_url' => env('GITHUB_API_BASE', 'https://api.github.com'),
    'api_version' => env('GITHUB_API_VERSION', '2022-11-28'),
    'user_agent' => env('GITHUB_USER_AGENT', 'Jarvis-OwlSolutions'),
    'timeout' => (int) env('GITHUB_HTTP_TIMEOUT', 10),
    'connect_timeout' => (int) env('GITHUB_HTTP_CONNECT_TIMEOUT', 5),
    'get_retries' => (int) env('GITHUB_GET_RETRIES', 1),
    'max_repositories' => (int) env('GITHUB_MAX_REPOSITORIES', 30),
    'max_branches' => (int) env('GITHUB_MAX_BRANCHES', 30),
    'max_commits' => (int) env('GITHUB_MAX_COMMITS', 20),
    'max_commit_files' => (int) env('GITHUB_MAX_COMMIT_FILES', 40),
    'max_file_chars' => (int) env('GITHUB_MAX_FILE_CHARS', 12000),
    'max_search_results' => (int) env('GITHUB_MAX_SEARCH', 15),
    'max_issues' => (int) env('GITHUB_MAX_ISSUES', 20),
    'max_issue_comments' => (int) env('GITHUB_MAX_ISSUE_COMMENTS', 10),
    'max_issue_body_chars' => (int) env('GITHUB_MAX_ISSUE_BODY', 4000),
    'max_comment_chars' => (int) env('GITHUB_MAX_COMMENT', 2000),
    'max_pull_requests' => (int) env('GITHUB_MAX_PULLS', 20),
    'max_pr_files' => (int) env('GITHUB_MAX_PR_FILES', 40),
    'max_workflow_runs' => (int) env('GITHUB_MAX_WORKFLOW_RUNS', 15),
    'max_workflow_jobs' => (int) env('GITHUB_MAX_WORKFLOW_JOBS', 20),
    'max_diff_chars' => (int) env('GITHUB_MAX_DIFF_CHARS', 8000),
    'max_patch_chars' => (int) env('GITHUB_MAX_PATCH_CHARS', 2000),
    'max_description_chars' => (int) env('GITHUB_MAX_DESCRIPTION', 240),
    'max_title_chars' => (int) env('GITHUB_MAX_TITLE', 256),
    'max_body_chars' => (int) env('GITHUB_MAX_BODY', 4000),
    'max_labels' => (int) env('GITHUB_MAX_LABELS', 10),
    'max_assignees' => (int) env('GITHUB_MAX_ASSIGNEES', 10),
    'max_candidates' => (int) env('GITHUB_MAX_CANDIDATES', 8),
    'default_branch_fallback' => env('GITHUB_DEFAULT_BRANCH_FALLBACK', 'main'),
    'allowed_write_operations' => [
        'create_issue',
        'comment_issue',
        'create_branch',
        'create_pull_request',
    ],
];
